# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b59941ce343b69c5b03b77ac53075b6b839348acb03a21ff90062677bf159ecec042bd4f02bc6446ccbc5a3bb2b380c83033ab278c44fe7375cc05890653d705

test:
  secret_key_base: 8139e6e4919383b06f69f41da91e0db2f137fc9f9d09e4c7b0a1bccf6b40fabc5154fc4c3022c4236cddd294db189e227d9b146b944bcb5a177114e15c9356c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
