require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CutoffsController do

  # This should return the minimal set of attributes required to create a valid
  # Cutoff. As you add validations to Cutoff, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "cutoff_at" => "2015-11-02 19:12:22" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CutoffsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cutoffs as @cutoffs" do
      cutoff = Cutoff.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cutoffs).should eq([cutoff])
    end
  end

  describe "GET show" do
    it "assigns the requested cutoff as @cutoff" do
      cutoff = Cutoff.create! valid_attributes
      get :show, {:id => cutoff.to_param}, valid_session
      assigns(:cutoff).should eq(cutoff)
    end
  end

  describe "GET new" do
    it "assigns a new cutoff as @cutoff" do
      get :new, {}, valid_session
      assigns(:cutoff).should be_a_new(Cutoff)
    end
  end

  describe "GET edit" do
    it "assigns the requested cutoff as @cutoff" do
      cutoff = Cutoff.create! valid_attributes
      get :edit, {:id => cutoff.to_param}, valid_session
      assigns(:cutoff).should eq(cutoff)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cutoff" do
        expect {
          post :create, {:cutoff => valid_attributes}, valid_session
        }.to change(Cutoff, :count).by(1)
      end

      it "assigns a newly created cutoff as @cutoff" do
        post :create, {:cutoff => valid_attributes}, valid_session
        assigns(:cutoff).should be_a(Cutoff)
        assigns(:cutoff).should be_persisted
      end

      it "redirects to the created cutoff" do
        post :create, {:cutoff => valid_attributes}, valid_session
        response.should redirect_to(Cutoff.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cutoff as @cutoff" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cutoff.any_instance.stub(:save).and_return(false)
        post :create, {:cutoff => { "cutoff_at" => "invalid value" }}, valid_session
        assigns(:cutoff).should be_a_new(Cutoff)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cutoff.any_instance.stub(:save).and_return(false)
        post :create, {:cutoff => { "cutoff_at" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cutoff" do
        cutoff = Cutoff.create! valid_attributes
        # Assuming there are no other cutoffs in the database, this
        # specifies that the Cutoff created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cutoff.any_instance.should_receive(:update).with({ "cutoff_at" => "2015-11-02 19:12:22" })
        put :update, {:id => cutoff.to_param, :cutoff => { "cutoff_at" => "2015-11-02 19:12:22" }}, valid_session
      end

      it "assigns the requested cutoff as @cutoff" do
        cutoff = Cutoff.create! valid_attributes
        put :update, {:id => cutoff.to_param, :cutoff => valid_attributes}, valid_session
        assigns(:cutoff).should eq(cutoff)
      end

      it "redirects to the cutoff" do
        cutoff = Cutoff.create! valid_attributes
        put :update, {:id => cutoff.to_param, :cutoff => valid_attributes}, valid_session
        response.should redirect_to(cutoff)
      end
    end

    describe "with invalid params" do
      it "assigns the cutoff as @cutoff" do
        cutoff = Cutoff.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cutoff.any_instance.stub(:save).and_return(false)
        put :update, {:id => cutoff.to_param, :cutoff => { "cutoff_at" => "invalid value" }}, valid_session
        assigns(:cutoff).should eq(cutoff)
      end

      it "re-renders the 'edit' template" do
        cutoff = Cutoff.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cutoff.any_instance.stub(:save).and_return(false)
        put :update, {:id => cutoff.to_param, :cutoff => { "cutoff_at" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cutoff" do
      cutoff = Cutoff.create! valid_attributes
      expect {
        delete :destroy, {:id => cutoff.to_param}, valid_session
      }.to change(Cutoff, :count).by(-1)
    end

    it "redirects to the cutoffs list" do
      cutoff = Cutoff.create! valid_attributes
      delete :destroy, {:id => cutoff.to_param}, valid_session
      response.should redirect_to(cutoffs_url)
    end
  end

end
